In [47]:
import random
import numpy as np
import os
import torch 

def set_seed(seed=24):
    """Setea semilla para reproducibilidad general"""
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    
    # PyTorch
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed) # si usas multi-GPU
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    print(f"Semilla fijada en: {seed}")

# Llamar a la función
set_seed(24)

Semilla fijada en: 24

In [48]:
import sys
sys.path.append('../')
 
import pandas as pd 
from sklearn.metrics import cohen_kappa_score, accuracy_score,balanced_accuracy_score
from plotly import express as px
from tutoriales.utils import plot_confusion_matrix, get_artifact_filename
from json import loads
from joblib import load, dump
import optuna
from optuna.artifacts import FileSystemArtifactStore, upload_artifact
from optuna.visualization import plot_param_importances
from optuna.importance import FanovaImportanceEvaluator
from optuna.visualization import plot_contour

In [49]:
import sys, numpy.core
# Shim: permite cargar joblib guardados con numpy >= 2.0 en entornos con numpy 1.x
sys.modules.setdefault("numpy._core", numpy.core)
for _sub in ["numeric", "multiarray", "umath", "fromnumeric", "arrayprint", "strings"]:
    mod = getattr(numpy.core, _sub, numpy.core)
    sys.modules.setdefault(f"numpy._core.{_sub}", mod)

In [50]:
# Paths
BASE_DIR = '../'
PATH_TO_TRAIN = os.path.join(BASE_DIR, "work/cleaned/train_clean.csv")
PATH_TO_TEMP_FILES = os.path.join(BASE_DIR, "work/optuna_temp_artifacts")
PATH_TO_OPTUNA_ARTIFACTS = os.path.join(BASE_DIR, "work/optuna_artifacts")

In [51]:
# Las predicciones del modelo LGB se guardan directamente como joblib
lgb_dataset = load(os.path.join(PATH_TO_TEMP_FILES, 'test_modelo_1__variables_originales.joblib'))
#lgb_dataset = load(os.path.join(PATH_TO_TEMP_FILES, 'test_modelo_2__variables_completas.joblib'))

In [52]:
MODEL_NAME = '01 DistilBert'
MODEL_VERSION = '5.0'

study_bert = optuna.create_study(direction='maximize',
                            storage="sqlite:///../work/db.sqlite3", 
                            study_name=f'{MODEL_NAME}_{MODEL_VERSION}',
                            load_if_exists = True)

[I 2026-05-09 00:38:02,518] Using an existing study with name '01 DistilBert_5.0' instead of creating a new one.

In [53]:
bert_dataset = load(os.path.join(PATH_TO_OPTUNA_ARTIFACTS,get_artifact_filename(study_bert,'test')))

In [54]:
# Cargar el modelo ResNet
MODEL_NAME_RESNET = '04 ResNet Augment'
MODEL_VERSION_RESNET = '1.0.0'

study_resnet = optuna.create_study(
    direction='maximize',
    storage="sqlite:///../work/optuna_artifacts/db.sqlite3",
    study_name=f'{MODEL_NAME_RESNET}_{MODEL_VERSION_RESNET}',
    load_if_exists=True
)

[I 2026-05-09 00:38:02,610] Using an existing study with name '04 ResNet Augment_1.0.0' instead of creating a new one.

In [55]:
resnet_dataset = load(os.path.join(PATH_TO_TEMP_FILES, 'test_04 ResNet Augment_1.0.0_1.joblib'))
#resnet_dataset = load(os.path.join(PATH_TO_TEMP_FILES,get_artifact_filename(study_resnet,'test')))

In [56]:
merged_datasets = lgb_dataset[['PetID', 'pred', 'AdoptionSpeed']].rename({'pred':'lgb_pred_score'},axis=1).merge(bert_dataset[['PetID', 'pred']].rename({'pred':'bert_pred_score'},axis=1),
                  on='PetID', how='outer')

In [57]:
# Unir ResNet al dataframe fusionado
merged_datasets = merged_datasets.merge(
    resnet_dataset[['PetID', 'pred']].rename({'pred': 'resnet_pred_score'}, axis=1),
    on='PetID', how='outer'
)

In [58]:
merged_datasets.head()

,PetID,lgb_pred_score,AdoptionSpeed,bert_pred_score,resnet_pred_score
0,002230dea,"[0.06175187846442381, 0.2940676868352113, 0.41...",1,"[0.009752763, 0.5465382, 0.43560302, 0.0048021...","[-0.99180895, 0.7428905, 0.48204118, 0.1142346..."
1,0063f83c9,"[0.08883536737434454, 0.16060991232554725, 0.2...",1,"[0.0020303065, 0.00568232, 0.088742584, 0.0133...","[-1.3278729, 0.98171896, -0.028774094, 0.35766..."
2,0073c33d0,"[0.006477767488363635, 0.222578069511566, 0.22...",3,"[0.0007240717, 0.016772836, 0.22749364, 0.7542...","[-1.4208313, 0.7716534, 1.2558718, 0.40233982,..."
3,00bfa5da9,"[0.008940191888288453, 0.09638043680171315, 0....",4,"[8.41588e-05, 0.00040059086, 0.0027940436, 0.0...","[-2.9708593, -0.9604822, 0.53046876, 0.9579238..."
4,00c19f4fa,"[0.020924012275847437, 0.12606051674692606, 0....",2,"[0.0014462878, 0.08401318, 0.8484335, 0.056610...","[-2.509712, 0.45661384, 0.80324507, 0.8857457,..."

In [59]:
merged_datasets.isnull().mean().mul(100).round(2).rename('% nulos')

PetID                0.00
lgb_pred_score       0.00
AdoptionSpeed        0.00
bert_pred_score      0.10
resnet_pred_score    2.27
Name: % nulos, dtype: float64

In [60]:
# Limpiar nulos (rellenar con arrays de ceros si algún modelo no tiene predicción para un PetID)
merged_datasets['resnet_pred_score'] = [np.zeros(5) if type(i) is float else i for i in merged_datasets['resnet_pred_score']]
merged_datasets['bert_pred_score']   = [np.zeros(5) if type(i) is float else i for i in merged_datasets['bert_pred_score']]
merged_datasets['lgb_pred_score']    = [np.zeros(5) if type(i) is float else i for i in merged_datasets['lgb_pred_score']]

In [61]:
all_values = [item for sublist in merged_datasets["resnet_pred_score"] for item in sublist]
min_val = min(all_values)
max_val = max(all_values)

def normalizar_lista(lista):
    return [(x - min_val) / (max_val - min_val) for x in lista]

merged_datasets["resnet_pred_score"] = merged_datasets["resnet_pred_score"].apply(normalizar_lista)

all_values1 = [item for sublist in merged_datasets["bert_pred_score"] for item in sublist]
min_val1 = min(all_values1)
max_val1 = max(all_values1)

def normalizar_lista1(lista):
    return [(x - min_val1) / (max_val1 - min_val1) for x in lista]

merged_datasets["bert_pred_score"] = merged_datasets["bert_pred_score"].apply(normalizar_lista1)

all_values2 = [item for sublist in merged_datasets["lgb_pred_score"] for item in sublist]
min_val2 = min(all_values2)
max_val2 = max(all_values2)

def normalizar_lista2(lista):
    return [(x - min_val2) / (max_val2 - min_val2) for x in lista]

merged_datasets["lgb_pred_score"] = merged_datasets["lgb_pred_score"].apply(normalizar_lista2)

In [62]:
merged_datasets.head()

,PetID,lgb_pred_score,AdoptionSpeed,bert_pred_score,resnet_pred_score
0,002230dea,"[0.06338951295469104, 0.3074418540495358, 0.43...",1,"[0.009764634848057976, 0.5472034399846415, 0.4...","[0.3858939, 0.60110545, 0.5687438, 0.5231127, ..."
1,0063f83c9,"[0.09184125250627968, 0.16724182833967538, 0.2...",1,"[0.0020327778574799906, 0.005689236591533274, ...","[0.3442009, 0.6307352, 0.5053706, 0.55331373, ..."
2,0073c33d0,"[0.00532296862330662, 0.2323406003115052, 0.23...",3,"[0.0007249530609934081, 0.016793252943771726, ...","[0.33266822, 0.60467386, 0.66474736, 0.5588558..."
3,00bfa5da9,"[0.007909794047651216, 0.09976749683027117, 0....",4,"[8.426123820892333e-05, 0.00040107846939244556...","[0.14036748, 0.3897804, 0.57475185, 0.6277831,..."
4,00c19f4fa,"[0.020499033847363714, 0.13094700650423355, 0....",2,"[0.001448048319537855, 0.08411544279376652, 0....","[0.19757868, 0.56558925, 0.6085932, 0.6188285,..."

In [63]:
# Optimización con Optuna para 3 pesos
def objective(trial):
    # Definir pesos para los tres modelos
    w_lgb = trial.suggest_float('w_lgb', 0.0, 1.0)
    w_bert = trial.suggest_float('w_bert', 0.0, 1.0)
    w_resnet = trial.suggest_float('w_resnet', 0.0, 1.0)
    
    # Normalización
    total_w = w_lgb + w_bert + w_resnet
    if total_w == 0: return 0
    
    # Cálculo vectorizado para mayor velocidad
    # Convertimos las columnas de scores en una matriz 3D o sumamos directamente
    lgb_scores = np.stack(merged_datasets['lgb_pred_score'].values)
    bert_scores = np.stack(merged_datasets['bert_pred_score'].values)
    resnet_scores = np.stack(merged_datasets['resnet_pred_score'].values)
    
    combined_scores = (
        (w_lgb / total_w) * lgb_scores + 
        (w_bert / total_w) * bert_scores + 
        (w_resnet / total_w) * resnet_scores
    )
    
    preds_final = np.argmax(combined_scores, axis=1)
    
    return cohen_kappa_score(merged_datasets['AdoptionSpeed'], preds_final, weights='quadratic')

In [64]:
# Ejecutar el estudio
STORAGE_URL = "sqlite:///../work/db.sqlite3"
study_blend = optuna.create_study(
    direction='maximize',
    storage=STORAGE_URL,
    study_name="Ensemble_LGB_BERT_ResNet",
    load_if_exists=True
)
study_blend.optimize(objective, n_trials=100)

[I 2026-05-09 00:38:02,791] Using an existing study with name 'Ensemble_LGB_BERT_ResNet' instead of creating a new one.
[I 2026-05-09 00:38:03,085] Trial 1701 finished with value: 0.3532692521828009 and parameters: {'w_lgb': 0.7087659607057254, 'w_bert': 0.1424328376465346, 'w_resnet': 0.17972517078675287}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,138] Trial 1702 finished with value: 0.3380931256326625 and parameters: {'w_lgb': 0.818626887139089, 'w_bert': 0.05599281166603747, 'w_resnet': 0.22111730482696185}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,200] Trial 1703 finished with value: 0.3578549926024428 and parameters: {'w_lgb': 0.636151390793837, 'w_bert': 0.1015288497195053, 'w_resnet': 0.2541242604205714}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,263] Trial 1704 finished with value: 0.3322043546459257 and parameters: {'w_lgb': 0.6865440682830056, 'w_bert': 0.6530439537613856, 'w_resnet': 0.28570275416171104}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,325] Trial 1705 finished with value: 0.3513985228023926 and parameters: {'w_lgb': 0.7289250091045855, 'w_bert': 0.174162396311382, 'w_resnet': 0.11555703700590726}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,381] Trial 1706 finished with value: 0.3565512552464013 and parameters: {'w_lgb': 0.6580495707676222, 'w_bert': 0.12763172755954516, 'w_resnet': 0.2007440865746653}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,436] Trial 1707 finished with value: 0.34381351086869516 and parameters: {'w_lgb': 0.6166271588919294, 'w_bert': 0.0813707354272325, 'w_resnet': 0.14147969704410007}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,492] Trial 1708 finished with value: 0.35502951253870196 and parameters: {'w_lgb': 0.673359764036975, 'w_bert': 0.11057880067421624, 'w_resnet': 0.2506857157265035}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,547] Trial 1709 finished with value: 0.36587048074833106 and parameters: {'w_lgb': 0.7003325486040791, 'w_bert': 0.03381117793920052, 'w_resnet': 0.9401675057217881}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,603] Trial 1710 finished with value: 0.36023936143748525 and parameters: {'w_lgb': 0.7723134584854447, 'w_bert': 0.1554928715245627, 'w_resnet': 0.28082285441365956}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,665] Trial 1711 finished with value: 0.36005565618308033 and parameters: {'w_lgb': 0.648128474256545, 'w_bert': 0.12925740810038192, 'w_resnet': 0.2234112603174852}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,721] Trial 1712 finished with value: 0.37064096845558514 and parameters: {'w_lgb': 0.7231352660550039, 'w_bert': 0.09154378446923996, 'w_resnet': 0.8104492263335366}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,777] Trial 1713 finished with value: 0.34362314672175165 and parameters: {'w_lgb': 0.7474696167283413, 'w_bert': 0.06766999445368577, 'w_resnet': 0.2658854277823342}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,832] Trial 1714 finished with value: 0.3588981348087664 and parameters: {'w_lgb': 0.6901656601736792, 'w_bert': 0.20299276535500466, 'w_resnet': 0.1672689972470334}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,888] Trial 1715 finished with value: 0.36510286810599046 and parameters: {'w_lgb': 0.6627354202417163, 'w_bert': 0.14304144761036874, 'w_resnet': 0.3051002593124686}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,936] Trial 1716 finished with value: 0.3442681326162842 and parameters: {'w_lgb': 0.7107899137386219, 'w_bert': 0.10660473279432187, 'w_resnet': 0.19288404675102763}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:03,992] Trial 1717 finished with value: 0.3596136170227071 and parameters: {'w_lgb': 0.6344022830498078, 'w_bert': 0.11918096738757501, 'w_resnet': 0.24583400893831775}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,050] Trial 1718 finished with value: 0.3465386281391827 and parameters: {'w_lgb': 0.6819719752407194, 'w_bert': 0.09025682358411308, 'w_resnet': 0.21366877089521785}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,103] Trial 1719 finished with value: 0.3592535477784641 and parameters: {'w_lgb': 0.7002573517738617, 'w_bert': 0.14137038006190647, 'w_resnet': 0.27034347474296444}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,159] Trial 1720 finished with value: 0.3401792413940532 and parameters: {'w_lgb': 0.7397051446162961, 'w_bert': 0.07182378404214357, 'w_resnet': 0.23799830107849826}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,214] Trial 1721 finished with value: 0.35852837061872267 and parameters: {'w_lgb': 0.6594146982861503, 'w_bert': 0.1644671625008264, 'w_resnet': 0.18235688953984563}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,264] Trial 1722 finished with value: 0.36052637571585233 and parameters: {'w_lgb': 0.6753510075167373, 'w_bert': 0.11328502828827101, 'w_resnet': 0.2880072959334355}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,322] Trial 1723 finished with value: 0.36183132682629704 and parameters: {'w_lgb': 0.6198837645805876, 'w_bert': 0.18370736915237973, 'w_resnet': 0.32859654481360767}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,381] Trial 1724 finished with value: 0.38394938409170465 and parameters: {'w_lgb': 0.47230676745730504, 'w_bert': 0.09783102455985271, 'w_resnet': 0.6995289159149612}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,437] Trial 1725 finished with value: 0.34259979783238603 and parameters: {'w_lgb': 0.8784223360724526, 'w_bert': 0.12834460251633373, 'w_resnet': 0.22727770696068234}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,499] Trial 1726 finished with value: 0.34857340734115183 and parameters: {'w_lgb': 0.6430469875260622, 'w_bert': 0.08329368343255485, 'w_resnet': 0.2552676241246105}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,555] Trial 1727 finished with value: 0.3591611004947133 and parameters: {'w_lgb': 0.5783866474790653, 'w_bert': 0.1436925567161711, 'w_resnet': 0.20867849809168165}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,611] Trial 1728 finished with value: 0.34448581334798234 and parameters: {'w_lgb': 0.7133447310133113, 'w_bert': 0.054979245202267886, 'w_resnet': 0.27155796737523075}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,672] Trial 1729 finished with value: 0.34355801884703163 and parameters: {'w_lgb': 0.6913906696457308, 'w_bert': 0.11580876292639357, 'w_resnet': 0.1527982935036201}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,728] Trial 1730 finished with value: 0.3511026947688817 and parameters: {'w_lgb': 0.665968544000686, 'w_bert': 0.09951012329009923, 'w_resnet': 0.23357383094685166}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,783] Trial 1731 finished with value: 0.3641151238587641 and parameters: {'w_lgb': 0.5153639796124391, 'w_bert': 0.13061452789154132, 'w_resnet': 0.30773182666742815}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,841] Trial 1732 finished with value: 0.3587970579771823 and parameters: {'w_lgb': 0.7286911377413662, 'w_bert': 0.1591653461677495, 'w_resnet': 0.19061213931600646}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,902] Trial 1733 finished with value: 0.343406490368123 and parameters: {'w_lgb': 0.64809059999261, 'w_bert': 0.044642530116656184, 'w_resnet': 0.25337103498158203}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:04,958] Trial 1734 finished with value: 0.33842153207640424 and parameters: {'w_lgb': 0.8104586793554134, 'w_bert': 0.07622365488025948, 'w_resnet': 0.2082728587674657}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,012] Trial 1735 finished with value: 0.3554622483724572 and parameters: {'w_lgb': 0.7036853692567994, 'w_bert': 0.10158804323634824, 'w_resnet': 0.280952879108387}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,076] Trial 1736 finished with value: 0.3485146431066606 and parameters: {'w_lgb': 0.7618205004748078, 'w_bert': 0.11742026438320545, 'w_resnet': 0.2304918663987365}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,131] Trial 1737 finished with value: 0.3572365654221663 and parameters: {'w_lgb': 0.6802379504427114, 'w_bert': 0.1496703596799914, 'w_resnet': 0.17020101319845438}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,186] Trial 1738 finished with value: 0.3530752232943999 and parameters: {'w_lgb': 0.6132124364628577, 'w_bert': 0.08421677523617435, 'w_resnet': 0.2515315741429272}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,246] Trial 1739 finished with value: 0.3499546615513681 and parameters: {'w_lgb': 0.8395150042274289, 'w_bert': 0.12925514050005943, 'w_resnet': 0.2953207407958502}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,299] Trial 1740 finished with value: 0.3547162459249781 and parameters: {'w_lgb': 0.6660764035345709, 'w_bert': 0.18310458280179945, 'w_resnet': 0.2197936281395302}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,353] Trial 1741 finished with value: 0.3436022023922536 and parameters: {'w_lgb': 0.8905926833425553, 'w_bert': 0.10816943796622454, 'w_resnet': 0.2666798636983851}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,416] Trial 1742 finished with value: 0.3394123989412654 and parameters: {'w_lgb': 0.6936385448768654, 'w_bert': 0.06575485678976906, 'w_resnet': 0.19528230992412843}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,473] Trial 1743 finished with value: 0.3591623657382349 and parameters: {'w_lgb': 0.719610267581468, 'w_bert': 0.1674151433708562, 'w_resnet': 0.23995636371552048}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,530] Trial 1744 finished with value: 0.3531076056817417 and parameters: {'w_lgb': 0.6443264207463537, 'w_bert': 0.13583906273320162, 'w_resnet': 0.14689832435448433}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,583] Trial 1745 finished with value: 0.34174662159968006 and parameters: {'w_lgb': 0.9294270345804665, 'w_bert': 0.09192006720228714, 'w_resnet': 0.26490038545305356}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,641] Trial 1746 finished with value: 0.3482019864597461 and parameters: {'w_lgb': 0.7413014864115249, 'w_bert': 0.11312318447226634, 'w_resnet': 0.21651103362782528}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,694] Trial 1747 finished with value: 0.35934199877062256 and parameters: {'w_lgb': 0.67573111020088, 'w_bert': 0.14685437164814583, 'w_resnet': 0.17815461131808571}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,750] Trial 1748 finished with value: 0.33800914965483975 and parameters: {'w_lgb': 0.7025883645414606, 'w_bert': 0.09287467931016921, 'w_resnet': 0.12756373728247425}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,804] Trial 1749 finished with value: 0.35023356591834853 and parameters: {'w_lgb': 0.7970881823133436, 'w_bert': 0.127568691673571, 'w_resnet': 0.24437225528546622}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,860] Trial 1750 finished with value: 0.3717631635852525 and parameters: {'w_lgb': 0.5410203773700326, 'w_bert': 0.25049028221635283, 'w_resnet': 0.28990797664342405}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,915] Trial 1751 finished with value: 0.3629143388210815 and parameters: {'w_lgb': 0.5963440353775993, 'w_bert': 0.1974008449733935, 'w_resnet': 0.20019933282316704}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:05,970] Trial 1752 finished with value: 0.34979355542301316 and parameters: {'w_lgb': 0.629655606330046, 'w_bert': 0.060374139839147786, 'w_resnet': 0.2728532877248285}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,026] Trial 1753 finished with value: 0.35514660164802925 and parameters: {'w_lgb': 0.6559312160931474, 'w_bert': 0.1142718325422708, 'w_resnet': 0.22971834844112732}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,082] Trial 1754 finished with value: 0.3462566519189719 and parameters: {'w_lgb': 0.6839968546364305, 'w_bert': 0.08832490398683758, 'w_resnet': 0.24875879517021648}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,138] Trial 1755 finished with value: 0.32229897684616815 and parameters: {'w_lgb': 0.8598392189790879, 'w_bert': 0.012692014707663776, 'w_resnet': 0.16382687265289764}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,197] Trial 1756 finished with value: 0.36281755938422655 and parameters: {'w_lgb': 0.7348740775804937, 'w_bert': 0.14316069592040986, 'w_resnet': 0.3207424233409984}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,263] Trial 1757 finished with value: 0.35710121587852617 and parameters: {'w_lgb': 0.7196193615489914, 'w_bert': 0.16401660944205376, 'w_resnet': 0.21483521921208854}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,329] Trial 1758 finished with value: 0.3470727926492111 and parameters: {'w_lgb': 0.6682614433964866, 'w_bert': 0.07217436000725823, 'w_resnet': 0.25791848295697223}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,399] Trial 1759 finished with value: 0.35687380277197556 and parameters: {'w_lgb': 0.6971144872473409, 'w_bert': 0.10340915941437512, 'w_resnet': 0.2947077966640272}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,465] Trial 1760 finished with value: 0.35668354076702735 and parameters: {'w_lgb': 0.6368342042577809, 'w_bert': 0.12653662181751474, 'w_resnet': 0.18300703433139498}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,532] Trial 1761 finished with value: 0.33890782611817105 and parameters: {'w_lgb': 0.6571799026063616, 'w_bert': 0.037577494648413, 'w_resnet': 0.23327526774783588}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,592] Trial 1762 finished with value: 0.36126074627599514 and parameters: {'w_lgb': 0.6829224918693304, 'w_bert': 0.11519178617908127, 'w_resnet': 0.2748372942985037}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,656] Trial 1763 finished with value: 0.3404777499022572 and parameters: {'w_lgb': 0.7711915392319825, 'w_bert': 0.0896149069159545, 'w_resnet': 0.20682953497118053}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,721] Trial 1764 finished with value: 0.3877480756132493 and parameters: {'w_lgb': 0.3241629848244947, 'w_bert': 0.1471663010128607, 'w_resnet': 0.25053753196501577}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,804] Trial 1765 finished with value: 0.36446605721650827 and parameters: {'w_lgb': 0.7107608950689998, 'w_bert': 0.22183599556642736, 'w_resnet': 0.3097399355564858}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,889] Trial 1766 finished with value: 0.35006056005637354 and parameters: {'w_lgb': 0.9090540113900338, 'w_bert': 0.10376908555136223, 'w_resnet': 0.3708641433126783}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:06,957] Trial 1767 finished with value: 0.3604265629403487 and parameters: {'w_lgb': 0.6724208722153392, 'w_bert': 0.17470365283496525, 'w_resnet': 0.2781214099447797}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,027] Trial 1768 finished with value: 0.34552120966986355 and parameters: {'w_lgb': 0.6205351005407569, 'w_bert': 0.07459688755723061, 'w_resnet': 0.22632441028740338}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,095] Trial 1769 finished with value: 0.3571202126765667 and parameters: {'w_lgb': 0.6966118283114118, 'w_bert': 0.1306129531017987, 'w_resnet': 0.19016900855908658}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,167] Trial 1770 finished with value: 0.3408252720728814 and parameters: {'w_lgb': 0.7498370032778803, 'w_bert': 0.060758548542491575, 'w_resnet': 0.23915233018797769}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,234] Trial 1771 finished with value: 0.35148411640729427 and parameters: {'w_lgb': 0.6452091000901354, 'w_bert': 0.12213451934409356, 'w_resnet': 0.15424736890423815}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,304] Trial 1772 finished with value: 0.3574329342055186 and parameters: {'w_lgb': 0.7205133870892019, 'w_bert': 0.15295249396984686, 'w_resnet': 0.26431717274158617}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,373] Trial 1773 finished with value: 0.34809042051177197 and parameters: {'w_lgb': 0.6631952471612208, 'w_bert': 0.1000002083768737, 'w_resnet': 0.20712338681627282}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,452] Trial 1774 finished with value: 0.35382473117587987 and parameters: {'w_lgb': 0.6876217823438792, 'w_bert': 0.08088626243633677, 'w_resnet': 0.3458797679907257}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,535] Trial 1775 finished with value: 0.36221708015810783 and parameters: {'w_lgb': 0.702419232042653, 'w_bert': 0.13154593988708768, 'w_resnet': 0.290182637384992}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,593] Trial 1776 finished with value: 0.3583154939017733 and parameters: {'w_lgb': 0.6510107525346794, 'w_bert': 0.10580555351376965, 'w_resnet': 0.25475869695683584}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,663] Trial 1777 finished with value: 0.3397794727202924 and parameters: {'w_lgb': 0.5993149362992086, 'w_bert': 0.05306245981625518, 'w_resnet': 0.17433395340529664}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,735] Trial 1778 finished with value: 0.3588545713678174 and parameters: {'w_lgb': 0.7311811049034441, 'w_bert': 0.161046246380698, 'w_resnet': 0.22278735465381533}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,797] Trial 1779 finished with value: 0.35592145674793296 and parameters: {'w_lgb': 0.6798935309179259, 'w_bert': 0.12009131102875534, 'w_resnet': 0.2407431997449841}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,860] Trial 1780 finished with value: 0.3407138669078923 and parameters: {'w_lgb': 0.8812504158426752, 'w_bert': 0.08613438948367724, 'w_resnet': 0.271949514739303}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,911] Trial 1781 finished with value: 0.358700386507645 and parameters: {'w_lgb': 0.630885752112916, 'w_bert': 0.142823807714671, 'w_resnet': 0.19365190791079412}. Best is trial 483 with value: 0.4235531747629919.
[I 2026-05-09 00:38:07,975] Trial 1782 finished with value: 0.34865826788329535 and parameters: {'w_lgb': 0.7110423477059958, 'w_bert': 0.10543637301956318, 'w_resnet': 0.22070590374965404}. Best is trial 483 with value: 0.4235531747629919.

In [65]:
# Resultados
best_params = study_blend.best_params
sum_best_w = sum(best_params.values())

print(f"Mejor Kappa: {study_blend.best_value:.4f}")
print(f"Pesos óptimos: {best_params}")

Mejor Kappa: 0.4236
Pesos óptimos: {'w_lgb': 0.6420695190692808, 'w_bert': 0.12797744543226441, 'w_resnet': 0.19324590533142716}

In [66]:
best_kappa = study_blend.best_trial.value
print(f"Mejor puntuación Kappa: {best_kappa}")

Mejor puntuación Kappa: 0.4235531747629919

In [67]:
# Crear la columna de predicción final optimizada

def _prediction_vector(value):
    if isinstance(value, (list, tuple, np.ndarray)):
        return np.asarray(value, dtype=float)
    return np.zeros(5, dtype=float)

merged_datasets['blend_pred_score'] = [
    (best_params['w_lgb'] / sum_best_w) * _prediction_vector(r['lgb_pred_score']) +
    (best_params['w_bert'] / sum_best_w) * _prediction_vector(r['bert_pred_score']) +
    (best_params['w_resnet'] / sum_best_w) * _prediction_vector(r['resnet_pred_score'])
    for _, r in merged_datasets.iterrows()
]

In [68]:
merged_datasets[['lgb_pred_score', 'bert_pred_score', 'resnet_pred_score']]

,lgb_pred_score,bert_pred_score,resnet_pred_score
0,"[0.06338951295469104, 0.3074418540495358, 0.43...","[0.009764634848057976, 0.5472034399846415, 0.4...","[0.3858939, 0.60110545, 0.5687438, 0.5231127, ..."
1,"[0.09184125250627968, 0.16724182833967538, 0.2...","[0.0020327778574799906, 0.005689236591533274, ...","[0.3442009, 0.6307352, 0.5053706, 0.55331373, ..."
2,"[0.00532296862330662, 0.2323406003115052, 0.23...","[0.0007249530609934081, 0.016793252943771726, ...","[0.33266822, 0.60467386, 0.66474736, 0.5588558..."
3,"[0.007909794047651216, 0.09976749683027117, 0....","[8.426123820892333e-05, 0.00040107846939244556...","[0.14036748, 0.3897804, 0.57475185, 0.6277831,..."
4,"[0.020499033847363714, 0.13094700650423355, 0....","[0.001448048319537855, 0.08411544279376652, 0....","[0.19757868, 0.56558925, 0.6085932, 0.6188285,..."
...,...,...,...
2994,"[0.06309052792363055, 0.3764763448547162, 0.15...","[0.0029909178783425424, 0.06526598962488048, 0...","[0.2567495, 0.52802324, 0.5217696, 0.56667143,..."
2995,"[0.2851502711379372, 0.18927432061548044, 0.34...","[0.0014949311689542628, 0.22506888091349558, 0...","[0.24999852, 0.5179931, 0.6030275, 0.5335944, ..."
2996,"[0.3074209837077267, 0.27131064076121053, 0.24...","[0.015637692593982188, 0.32118321502428354, 0....","[0.20750931, 0.67806304, 0.6485008, 0.5761223,..."
2997,"[0.03476466291855015, 0.6590189508734386, 0.14...","[0.0007484671007292614, 0.019214953625744838, ...","[0.3344465, 0.51293564, 0.5606445, 0.54551184,..."
2998,"[0.044168422924473205, 0.16310129501530116, 0....","[0.002709691182288237, 0.23359417142358582, 0....","[0.20229873, 0.53401774, 0.5996171, 0.6427012,..."

In [69]:
#merged_datasets['blend_pred_score']

In [70]:
plot_confusion_matrix(merged_datasets['AdoptionSpeed'],
                      merged_datasets['lgb_pred_score'].apply(np.argmax), 
                    title = 'LGB Model Kappa: ' + str(cohen_kappa_score(merged_datasets['AdoptionSpeed'],
                                                                    merged_datasets['lgb_pred_score'].apply(np.argmax), 
                                                                    weights='quadratic')))

In [71]:
plot_confusion_matrix(merged_datasets['AdoptionSpeed'],
                      merged_datasets['bert_pred_score'].apply(np.argmax), 
                    title = 'Bert Model Kappa: ' + str(cohen_kappa_score(merged_datasets['AdoptionSpeed'],
                                                                   merged_datasets['bert_pred_score'].apply(np.argmax), 
                                                                    weights='quadratic')))

In [72]:
plot_confusion_matrix(merged_datasets['AdoptionSpeed'],
                      merged_datasets['resnet_pred_score'].apply(np.argmax), 
                    title = 'ResNet Model Kappa: ' + str(cohen_kappa_score(merged_datasets['AdoptionSpeed'],
                                                                   merged_datasets['resnet_pred_score'].apply(np.argmax), 
                                                                    weights='quadratic')))

In [73]:
plot_confusion_matrix(merged_datasets['AdoptionSpeed'],
                      merged_datasets['blend_pred_score'].apply(np.argmax), 
                    title = 'Blended Model Kappa: ' + str(cohen_kappa_score(merged_datasets['AdoptionSpeed'],
                                                                   merged_datasets['blend_pred_score'].apply(np.argmax), 
                                                                    weights='quadratic')))

In [74]:
fig = plot_param_importances(study_blend, evaluator= FanovaImportanceEvaluator(seed=24))
fig.update_layout(
    title="Importancia de los Modelos en el Ensamble",
    xaxis_title="Importancia relativa",
    yaxis_title="Modelos",
    template="plotly_white"
)
fig.show()

In [75]:
#fig_contour = plot_contour(study_blend, params=['w_lgb', 'w_bert', 'w_resnet'])

#fig_contour.update_layout(
#    title="Interacción de Pesos y Rendimiento (Kappa)",
#    width=900,
#    height=800
#)

#fig_contour.show()

In [76]:
# Guardar el resultado final en un archivo temporal y subirlo a Optuna
final_filename = "merged_predictions_optimized.joblib"
dump(merged_datasets, final_filename)

['merged_predictions_optimized.joblib']

In [77]:
# Subir el archivo como artefacto del mejor trial
#artifact_store = FileSystemArtifactStore(base_path=PATH_TO_OPTUNA_ARTIFACTS)
#upload_artifact(
#    trial=study_blend.best_trial, 
#    file_path=final_filename, 
#    artifact_store=artifact_store
#)